<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rmod [
        <!ELEMENT rmod (block|chain|include)*>
        <!ELEMENT block (name,mtbf,mtbr,effect,failure,cost)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT mtbf (#PCDATA)>
        <!ELEMENT mtbr (#PCDATA)>
        <!ELEMENT effect (#PCDATA)>
        <!ELEMENT failure (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT chain (name,first,last,element+)>
        <!ELEMENT first (#PCDATA)>
        <!ELEMENT last (#PCDATA)>
        <!ELEMENT element (type,label,(child|parent)*)>
        <!ATTLIST element
                etype (block|chain) #REQUIRED>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT label (#PCDATA)>
        <!ELEMENT child (#PCDATA)>
        <!ELEMENT parent (#PCDATA)>
        <!ELEMENT include (#PCDATA)>
        ]>
<rmod>
    <block>
        <name>block a</name>
        <mtbf>0.96</mtbf>
        <mtbr>21</mtbr>
        <effect>3.14</effect>
        <failure>critical</failure>
        <cost>2</cost>
    </block>

    <include>../input2/extra_block.xml</include>

    <chain>
        <name>chain D</name>
        <first>first</first>
        <last>last</last>

        <element etype="block">
            <type>block a</type>
            <label>last</label>
            <parent>s2</parent>
            <parent>s3</parent>
        </element>
        <element etype="block">
            <type>block a</type>
            <label>first</label>
            <child>s2</child>
            <child>s3</child>
        </element>
        <element etype="block">
            <type>block a</type>
            <label>s2</label>
            <parent>first</parent>
            <child>last</child>
        </element>
        <element etype="block">
            <type>block a</type>
            <label>s3</label>
            <parent>first</parent>
            <child>last</child>
        </element>
    </chain>

    <chain>
        <name>chain E</name>
        <first>first</first>
        <last>last</last>

        <element etype="block">
            <type>block a</type>
            <label>first</label>
            <child>s2</child>
            <child>s3</child>
            <child>s4</child>
        </element>
        <element etype="block">
            <type>block a</type>
            <label>s2</label>
            <parent>first</parent>
            <child>last</child>
        </element>
        <element etype="block">
            <type>block a</type>
            <label>s3</label>
            <parent>first</parent>
            <child>last</child>
        </element>
        <element etype="block">
            <type>block a</type>
            <label>s4</label>
            <parent>first</parent>
            <child>last</child>
        </element>
        <element etype="block">
            <type>block a</type>
            <label>last</label>
            <parent>s2</parent>
            <parent>s3</parent>
            <parent>s4</parent>
        </element>
    </chain>

    <chain>
        <name>chain C</name>
        <first>only</first>
        <last>you</last>

        <element etype="block">
            <type>block a</type>
            <label>only</label>
            <child>you</child>
        </element>

        <element etype="block">
            <type>funni block</type>
            <label>you</label>
            <parent>only</parent>
        </element>
    </chain>

    <chain>
        <name>chain B</name>
        <first>one</first>
        <last>two</last>

        <element etype="chain">
            <type>chain D</type>
            <label>one</label>
            <child>two</child>
        </element>
        <element etype="chain">
            <type>chain E</type>
            <label>two</label>
            <parent>one</parent>
        </element>
    </chain>

    <chain>
        <name>chain A</name>
        <first>head</first>
        <last>tail</last>

        <element etype="block">
            <type>block a</type>
            <label>head</label>
            <child>c1</child>
            <child>c2</child>
        </element>

        <element etype="block">
            <type>block a</type>
            <label>tail</label>
            <parent>c1</parent>
            <parent>c2</parent>
        </element>

        <element etype="chain">
            <type>chain B</type>
            <label>c1</label>
            <parent>head</parent>
            <child>tail</child>
        </element>
        <element etype="chain">
            <type>chain C</type>
            <label>c2</label>
            <parent>head</parent>
            <child>tail</child>
        </element>
    </chain>
</rmod>
