<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rmod [
        <!ELEMENT rmod (block|chain|include)*>
        <!ELEMENT block (name,mtbf,effect,failure,cost)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT mtbf (#PCDATA)>
        <!ELEMENT effect (#PCDATA)>
        <!ELEMENT failure (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT chain (name,first,last,element+)>
        <!ELEMENT first (#PCDATA)>
        <!ELEMENT last (#PCDATA)>
        <!ELEMENT element (type,label,(child|parent)*)>
        <!ATTLIST element
                etype (block|chain) #REQUIRED>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT label (#PCDATA)>
        <!ELEMENT child (#PCDATA)>
        <!ELEMENT parent (#PCDATA)>
        <!ELEMENT include (#PCDATA)>
        ]>
<rmod>

        <block>
                <name>blades</name>
                <mtbf>0.980000</mtbf>
                <effect>1.000000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <block>
                <name>shaft</name>
                <mtbf>25.000000</mtbf>
                <effect>1.000000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <block>
                <name>mechanical break</name>
                <mtbf>100.000000</mtbf>
                <effect>1.000000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <block>
                <name>hub</name>
                <mtbf>14.290000</mtbf>
                <effect>1.000000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <chain>
                <name>column</name>
                <first>turbine blades</first>
                <last>shaft hub</last>

                <element etype="block">
                        <type>blades</type>
                        <label>turbine blades</label>
                        <child>shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>shaft core</label>
                        <parent>turbine blades</parent>
                        <child>mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>mech break</label>
                        <parent>shaft core</parent>
                        <child>shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>shaft hub</label>
                        <parent>mech break</parent>
                </element>
        </chain>
        <block>
                <name>gearbox</name>
                <mtbf>6.670000</mtbf>
                <effect>1.000000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <block>
                <name>DFIG</name>
                <mtbf>8.330000</mtbf>
                <effect>1.000000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <block>
                <name>converter</name>
                <mtbf>10.000000</mtbf>
                <effect>1.000000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <chain>
                <name>drive train</name>
                <first>dt gearbox</first>
                <last>dt converter</last>

                <element etype="block">
                        <type>gearbox</type>
                        <label>dt gearbox</label>
                        <child>dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>dt generator</label>
                        <parent>dt gearbox</parent>
                        <child>dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>dt converter</label>
                        <parent>dt generator</parent>
                </element>
        </chain>
        <block>
                <name>placeholder</name>
                <mtbf>0.000000</mtbf>
                <effect>1.000000</effect>
                <failure>normal</failure>
                <cost>0.000000</cost>
        </block>
        <block>
                <name>hydraulic</name>
                <mtbf>4.760000</mtbf>
                <effect>0.350000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <block>
                <name>anemometer</name>
                <mtbf>25.000000</mtbf>
                <effect>0.250000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <block>
                <name>sensors</name>
                <mtbf>11.110000</mtbf>
                <effect>0.100000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <block>
                <name>yaw system</name>
                <mtbf>33.330002</mtbf>
                <effect>0.300000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <block>
                <name>other</name>
                <mtbf>3.850000</mtbf>
                <effect>0.100000</effect>
                <failure>normal</failure>
                <cost>1.000000</cost>
        </block>
        <chain>
                <name>turbine</name>
                <first>in</first>
                <last>out2</last>

                <element etype="block">
                        <type>placeholder</type>
                        <label>in</label>
                        <child>column00::turbine blades</child>
                        <child>column01::turbine blades</child>
                        <child>column02::turbine blades</child>
                        <child>column03::turbine blades</child>
                        <child>column04::turbine blades</child>
                        <child>column05::turbine blades</child>
                        <child>column06::turbine blades</child>
                        <child>column07::turbine blades</child>
                        <child>column08::turbine blades</child>
                        <child>column09::turbine blades</child>
                        <child>column10::turbine blades</child>
                        <child>column11::turbine blades</child>
                        <child>column12::turbine blades</child>
                        <child>column13::turbine blades</child>
                        <child>column14::turbine blades</child>
                        <child>column15::turbine blades</child>
                        <child>column16::turbine blades</child>
                        <child>column17::turbine blades</child>
                        <child>column18::turbine blades</child>
                        <child>column19::turbine blades</child>
                        <child>column20::turbine blades</child>
                        <child>column21::turbine blades</child>
                        <child>column22::turbine blades</child>
                        <child>column23::turbine blades</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column00::turbine blades</label>
                        <parent>in</parent>
                        <child>column00::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column00::shaft core</label>
                        <parent>column00::turbine blades</parent>
                        <child>column00::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column00::mech break</label>
                        <parent>column00::shaft core</parent>
                        <child>column00::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column00::shaft hub</label>
                        <parent>column00::mech break</parent>
                        <child>drivetrain00::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain00::dt gearbox</label>
                        <parent>column00::shaft hub</parent>
                        <child>drivetrain00::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain00::dt generator</label>
                        <parent>drivetrain00::dt gearbox</parent>
                        <child>drivetrain00::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain00::dt converter</label>
                        <parent>drivetrain00::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column01::turbine blades</label>
                        <parent>in</parent>
                        <child>column01::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column01::shaft core</label>
                        <parent>column01::turbine blades</parent>
                        <child>column01::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column01::mech break</label>
                        <parent>column01::shaft core</parent>
                        <child>column01::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column01::shaft hub</label>
                        <parent>column01::mech break</parent>
                        <child>drivetrain01::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain01::dt gearbox</label>
                        <parent>column01::shaft hub</parent>
                        <child>drivetrain01::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain01::dt generator</label>
                        <parent>drivetrain01::dt gearbox</parent>
                        <child>drivetrain01::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain01::dt converter</label>
                        <parent>drivetrain01::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column02::turbine blades</label>
                        <parent>in</parent>
                        <child>column02::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column02::shaft core</label>
                        <parent>column02::turbine blades</parent>
                        <child>column02::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column02::mech break</label>
                        <parent>column02::shaft core</parent>
                        <child>column02::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column02::shaft hub</label>
                        <parent>column02::mech break</parent>
                        <child>drivetrain02::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain02::dt gearbox</label>
                        <parent>column02::shaft hub</parent>
                        <child>drivetrain02::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain02::dt generator</label>
                        <parent>drivetrain02::dt gearbox</parent>
                        <child>drivetrain02::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain02::dt converter</label>
                        <parent>drivetrain02::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column03::turbine blades</label>
                        <parent>in</parent>
                        <child>column03::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column03::shaft core</label>
                        <parent>column03::turbine blades</parent>
                        <child>column03::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column03::mech break</label>
                        <parent>column03::shaft core</parent>
                        <child>column03::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column03::shaft hub</label>
                        <parent>column03::mech break</parent>
                        <child>drivetrain03::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain03::dt gearbox</label>
                        <parent>column03::shaft hub</parent>
                        <child>drivetrain03::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain03::dt generator</label>
                        <parent>drivetrain03::dt gearbox</parent>
                        <child>drivetrain03::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain03::dt converter</label>
                        <parent>drivetrain03::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column04::turbine blades</label>
                        <parent>in</parent>
                        <child>column04::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column04::shaft core</label>
                        <parent>column04::turbine blades</parent>
                        <child>column04::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column04::mech break</label>
                        <parent>column04::shaft core</parent>
                        <child>column04::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column04::shaft hub</label>
                        <parent>column04::mech break</parent>
                        <child>drivetrain04::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain04::dt gearbox</label>
                        <parent>column04::shaft hub</parent>
                        <child>drivetrain04::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain04::dt generator</label>
                        <parent>drivetrain04::dt gearbox</parent>
                        <child>drivetrain04::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain04::dt converter</label>
                        <parent>drivetrain04::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column05::turbine blades</label>
                        <parent>in</parent>
                        <child>column05::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column05::shaft core</label>
                        <parent>column05::turbine blades</parent>
                        <child>column05::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column05::mech break</label>
                        <parent>column05::shaft core</parent>
                        <child>column05::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column05::shaft hub</label>
                        <parent>column05::mech break</parent>
                        <child>drivetrain05::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain05::dt gearbox</label>
                        <parent>column05::shaft hub</parent>
                        <child>drivetrain05::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain05::dt generator</label>
                        <parent>drivetrain05::dt gearbox</parent>
                        <child>drivetrain05::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain05::dt converter</label>
                        <parent>drivetrain05::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column06::turbine blades</label>
                        <parent>in</parent>
                        <child>column06::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column06::shaft core</label>
                        <parent>column06::turbine blades</parent>
                        <child>column06::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column06::mech break</label>
                        <parent>column06::shaft core</parent>
                        <child>column06::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column06::shaft hub</label>
                        <parent>column06::mech break</parent>
                        <child>drivetrain06::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain06::dt gearbox</label>
                        <parent>column06::shaft hub</parent>
                        <child>drivetrain06::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain06::dt generator</label>
                        <parent>drivetrain06::dt gearbox</parent>
                        <child>drivetrain06::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain06::dt converter</label>
                        <parent>drivetrain06::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column07::turbine blades</label>
                        <parent>in</parent>
                        <child>column07::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column07::shaft core</label>
                        <parent>column07::turbine blades</parent>
                        <child>column07::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column07::mech break</label>
                        <parent>column07::shaft core</parent>
                        <child>column07::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column07::shaft hub</label>
                        <parent>column07::mech break</parent>
                        <child>drivetrain07::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain07::dt gearbox</label>
                        <parent>column07::shaft hub</parent>
                        <child>drivetrain07::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain07::dt generator</label>
                        <parent>drivetrain07::dt gearbox</parent>
                        <child>drivetrain07::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain07::dt converter</label>
                        <parent>drivetrain07::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column08::turbine blades</label>
                        <parent>in</parent>
                        <child>column08::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column08::shaft core</label>
                        <parent>column08::turbine blades</parent>
                        <child>column08::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column08::mech break</label>
                        <parent>column08::shaft core</parent>
                        <child>column08::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column08::shaft hub</label>
                        <parent>column08::mech break</parent>
                        <child>drivetrain08::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain08::dt gearbox</label>
                        <parent>column08::shaft hub</parent>
                        <child>drivetrain08::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain08::dt generator</label>
                        <parent>drivetrain08::dt gearbox</parent>
                        <child>drivetrain08::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain08::dt converter</label>
                        <parent>drivetrain08::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column09::turbine blades</label>
                        <parent>in</parent>
                        <child>column09::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column09::shaft core</label>
                        <parent>column09::turbine blades</parent>
                        <child>column09::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column09::mech break</label>
                        <parent>column09::shaft core</parent>
                        <child>column09::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column09::shaft hub</label>
                        <parent>column09::mech break</parent>
                        <child>drivetrain09::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain09::dt gearbox</label>
                        <parent>column09::shaft hub</parent>
                        <child>drivetrain09::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain09::dt generator</label>
                        <parent>drivetrain09::dt gearbox</parent>
                        <child>drivetrain09::dt converter</child>
                </element>

                <element etype="block">
                        <type>converter</type>
                        <label>drivetrain09::dt converter</label>
                        <parent>drivetrain09::dt generator</parent>
                        <child>out</child>
                </element>

                <element etype="block">
                        <type>blades</type>
                        <label>column10::turbine blades</label>
                        <parent>in</parent>
                        <child>column10::shaft core</child>
                </element>

                <element etype="block">
                        <type>shaft</type>
                        <label>column10::shaft core</label>
                        <parent>column10::turbine blades</parent>
                        <child>column10::mech break</child>
                </element>

                <element etype="block">
                        <type>mechanical break</type>
                        <label>column10::mech break</label>
                        <parent>column10::shaft core</parent>
                        <child>column10::shaft hub</child>
                </element>

                <element etype="block">
                        <type>hub</type>
                        <label>column10::shaft hub</label>
                        <parent>column10::mech break</parent>
                        <child>drivetrain10::dt gearbox</child>
                </element>

                <element etype="block">
                        <type>gearbox</type>
                        <label>drivetrain10::dt gearbox</label>
                        <parent>column10::shaft hub</parent>
                        <child>drivetrain10::dt generator</child>
                </element>

                <element etype="block">
                        <type>DFIG</type>
                        <label>drivetrain10::dt generator</label>