<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rmod [
        <!ELEMENT rmod (block|chain|include)*>
        <!ELEMENT block (name,mtbf,mtbr,effect,failure,cost)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT mtbf (#PCDATA)>
        <!ELEMENT mtbr (#PCDATA)>
        <!ELEMENT effect (#PCDATA)>
        <!ELEMENT failure (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT chain (name,first,last,element+)>
        <!ELEMENT first (#PCDATA)>
        <!ELEMENT last (#PCDATA)>
        <!ELEMENT element (type,label,(child|parent)*)>
        <!ATTLIST element
                etype (block|chain) #REQUIRED>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT label (#PCDATA)>
        <!ELEMENT child (#PCDATA)>
        <!ELEMENT parent (#PCDATA)>
        <!ELEMENT include (#PCDATA)>
        ]>
<rmod>
    <block>
        <name>gearbox</name>
        <mtbf>6.67</mtbf>
        <mtbr>0.0001</mtbr>
        <effect>1.0</effect>
        <failure>critical</failure>
        <cost>1</cost>
    </block>

    <block>
        <name>DFIG</name>
        <mtbf>8.33</mtbf>
        <mtbr>0.0001</mtbr>
        <effect>1.0</effect>
        <failure>critical</failure>
        <cost>1</cost>
    </block>

    <block>
        <name>converter</name>
        <mtbf>10</mtbf>
        <mtbr>0.0001</mtbr>
        <effect>1.0</effect>
        <failure>critical</failure>
        <cost>1</cost>
    </block>

    <chain>
        <name>drive train</name>
        <first>dt gearbox</first>
        <last>dt converter</last>
        <element etype="block">
            <type>gearbox</type>
            <label>dt gearbox</label>
            <child>dt generator</child>
        </element>
        <element etype="block">
            <type>DFIG</type>
            <label>dt generator</label>
            <parent>dt gearbox</parent>
            <child>dt converter</child>
        </element>
        <element etype="block">
            <type>converter</type>
            <label>dt converter</label>
            <parent>dt generator</parent>
        </element>
    </chain>
</rmod>