<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rmod [
        <!ELEMENT rmod (block|chain|include)*>
        <!ELEMENT block (name,mtbf,effect,failure,cost)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT mtbf (#PCDATA)>
        <!ELEMENT effect (#PCDATA)>
        <!ELEMENT failure (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT chain (name,first,last,element+)>
        <!ELEMENT first (#PCDATA)>
        <!ELEMENT last (#PCDATA)>
        <!ELEMENT element (type,label,(child|parent)*)>
        <!ATTLIST element
                etype (block|chain) #REQUIRED>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT label (#PCDATA)>
        <!ELEMENT child (#PCDATA)>
        <!ELEMENT parent (#PCDATA)>
        <!ELEMENT include (#PCDATA)>
        ]>
<rmod>
    <block>
        <name>pump</name>
        <mtbf>0.96</mtbf>
        <effect>3.14</effect>
        <failure>critical</failure>
        <cost>10</cost>
    </block>

    <block>
        <name>refinery</name>
        <mtbf>0.9</mtbf>
        <effect>0.5</effect>
        <failure>normal</failure>
        <cost>200</cost>
    </block>

    <chain>
        <name>master</name>
        <first>master_pump</first>
        <last>stage_two_refinery</last>

        <element etype="block">
            <type>pump</type>
            <label>master_pump</label>
            <child>stage_one_refinery_1</child>
            <child>stage_one_refinery_2</child>
        </element>

        <element etype="block">
            <type>refinery</type>
            <label>stage_one_refinery_1</label>
            <parent>master_pump</parent>
            <child>stage_two_refinery</child>
        </element>

        <element etype="block">
            <type>refinery</type>
            <label>stage_one_refinery_2</label>
            <parent>master_pump</parent>
            <child>stage_two_refinery</child>
        </element>

        <element etype="block">
            <type>refinery</type>
            <label>stage_two_refinery</label>
            <parent>stage_one_refinery_1</parent>
            <parent>stage_one_refinery_2</parent>
        </element>
    </chain>
</rmod>
